### ISSUE TITLE
Fix MPAS e2e Test Suite

### ISSUE THREAD

**Issue by shivenduverma-sap** [open-component-model/MPAS#56]
Improvements>
- Cover all stages from the mpas event diagram
- Introduce waits for all check conditions

Acceptance Criteria:
- e2e tests are run for every PR

**Comment by shivenduverma-sap** [comment]
Also added fixes for the following bugs:
- Added "productdescription" in the project role
- target was being created in the project namespace, despite the definition in metadata.namespace, but while looking up the target with the selector, it was always looked up in mpas-system namespace. Changed the lookup to use namespace in metadata.namespace. 
- Added nil check in localization controller

**Comment by Skarlso** [comment]
>target was being created in the project namespace, despite the definition in metadata.namespace, but while looking up the target with the selector, it was always looked up in mpas-system namespace. Changed the lookup to use namespace in metadata.namespace.

That is incorrect. The test was wrong in that case. The `Target` object lives in the mpas-system namespace.
