### ISSUE TITLE
MPAS CLI Binary Release Process

### ISSUE THREAD

**Issue by souleb** [open-component-model/MPAS#59]
We should provide a way to install `mpas cli`. This issue tracks the needed tasks in order to do so:
- [x] set up the mpas cli binary release process
- [x] provide a shell script to install the cli
- [x] provide documentation on how to install and bootstrap with `mpas`
- [x] provide a `brew` recipe for `mac`

**Comment by robertwol** [comment]
`brew install open-component-model/tap/mpas`  exists
@souleb could you link the PRs back to this issue?

**Comment by robertwol** [comment]
@souleb what is the use case for the :  _**provide a shell script to install the cli**_
