### ISSUE TITLE
Unresolved issues - configure credentials appropriately on the Project Service Account

### ISSUE THREAD

**Issue by robertwol** [open-component-model/MPAS#76]
Is this still relevant @phoban01 

**[Unresolved issues](https://github.com/open-component-model/MPAS/blob/main/docs/concepts/projects.md#unresolved-issues)**

How to configure credentials appropriately on the Project Service Account? Ideally, we would use a mechanism similar to EKS IRSA. This would enable us to avoid storing long-lived credentials in the cluster.

**Comment by Skarlso** [comment]
Yep. This is still relevant. We have an issue here: https://github.com/open-component-model/MPAS/issues/47

**Comment by Skarlso** [comment]
Closing this in favour of #47 and also, we now have an automatic way of keeping track of the secrets to add to our project service account in this PR: https://github.com/open-component-model/mpas-project-controller/pull/36
