### ISSUE TITLE
Feature Request: Dependency between Pipelines

### ISSUE THREAD

**Issue by shivenduverma-sap** [open-component-model/MPAS#78]
There should be a way to prioritise the order in which the parts of the pipeline are deployed via a priority(int) flag. The idea is to simulate the depends functionality but priority also allows bundling.

The following features should be supported:
- Priority
  - multiple pipelines could have the same priority (to support bundles/stages) 
  - default priority is 1

**Comment by Skarlso** [comment]
Hello.

I'm not following this, sorry. Could you elaborate please what pipelines you are talking about here?

**Comment by robertwol** [comment]
As per discussion with  @shivenduverma-sap it is Not relevant anymore.
